# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
# https://circleci.com/developer/orbs/orb/coveralls/coveralls
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.14

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    parallelism: 4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i

      - run: npm run pre-commit

      - run: npm test

      - run: npm run build

      - run: npm run link

      # - run: npm run e-tsc

      - coveralls/upload

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

# https://dev.to/dxnchima/integrating-circleci-with-coveralls-for-your-next-node-project-hi1
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
