name: GitHub Actions
on: [push]
jobs:
  Build_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.14'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm i
    - run: npm run pre-commit
      name: check type, run lint --fix and prettier
    - run: npm test
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
    - run: npm run build
    - run: npm run link
    - run: npm run e-tsc
      name: check codeForDoc type
    - uses: codecov/codecov-action@v2
    