name: GitHub Actions
on: [push]
jobs:
  Build_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.14'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm i
    - run: npm run pre-commit
    - run: npm test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
    - run: npm run build
    - run: npm run e-tsc